name: CD
on:
  push:
    branches:
      - seminario-everton
      - master
    pull_request_target:
      types: [assigned, opened, synchronize, reopened]

jobs:
  deploy:
    name: deploy-cdms
    runs-on: ubuntu-latest

    steps:
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: "AKIAVE6VFYVVHLDB4VPE"
        aws-secret-access-key: "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"
        aws-region: us-east-2

    - name: att git ...
      run: |
        cd /var/www/cdms/
        git pull origin seminario-everton
        git status
